# Generated by Django 4.2.15 on 2024-08-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaBairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('veiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('placa', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NovaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NovoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.novacategoria')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.novovalor')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('identificador_unico', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipovenda')),
            ],
        ),
        migrations.CreateModel(
            name='VendaDoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='DadosVendaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.CharField(blank=True, max_length=100, null=True)),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atendente')),
            ],
        ),
        migrations.CreateModel(
            name='DadosRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_cliente', models.IntegerField(blank=True, null=True)),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='DadosEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_cliente', models.IntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('pontoReferencia', models.CharField(blank=True, max_length=100, null=True)),
                ('bairroPadrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entregabairro')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entregador')),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
    ]
